language: go

sudo: false

go:
  - 1.8

script: 
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -update
  - make build
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false