#!/bin/bash

GOROOT=`go env GOROOT`
SRCROOT="$GOROOT/src"
MODULES=`find $SRCROOT -name \*.go | xargs -L 1 dirname | sort -u | sed s\0^$SRCROOT/\0\0 | grep -v "^vendor/" | sed 's/^.*$/"&",/'`

gofmt <<EOF >standard_go_packages.go
//go:generate ./regen.sh

package depbleed

// This list was auto-generated by running \`go generate\`.
//
// You should probably re-do it on every Go release and commit the result.
var standardGoPackages = []string{
$MODULES
}
EOF
